config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'author'
  root to: "blogs#index"
  
  resources :blogs, only:[:index, :show, :genre, :owner] do
    collection do
      get 'search'
    end
  end

  namespace :admin, path: 'author' do
    resources :blogs, only: [:new, :create, :edit, :update, :destroy]
  end

  get '/blogs/genre/:id', to: "blogs#genre"
  get 'owner', action: :owner, controller: 'blogs'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre


  belongs_to :user
  has_one_attached :image

  with_options presence: true do
    validates :title
    validates :text
    validates :image
    validates :genre_id, numericality: { other_than: 1 } 
  end

  def was_attached?
    self.image.attached?
  end

  def self.search(search)
    if search != ""
      Blog.where('title LIKE(?)', "%#{search}%")
    else
      Blog.all
    end
  end

end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '---'},
    { id: 2, name: 'Java' },
    { id: 3, name: 'Minecraft' },
  ]

  include ActiveHash::Associations
  has_many :blogs

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < ApplicationController
  before_action :if_not_admin
  before_action :set_blog, only: [:edit, :update, :destroy]
  
  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      flash[:notice] = "Success!"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    
    @blog.update(blog_update)
    if @blog.valid?
      flash[:notice] = "Success!"
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    
    @blog.destroy
    redirect_to root_path
  end


  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end

  def blog_params
    params.permit(:title, :genre_id, :image, :text, :description).merge(user_id: current_user.id)
  end

  def blog_update
    params.require(:blog).permit(:title, :genre_id, :image, :text, :description).merge(user_id: current_user.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  

  def index
    #@blogs = Blog.page(params[:page]).per(10)
    @blogs = Blog.all.order(created_at: :desc).page(params[:page]).per(5)
    #@posts = Post.all.order(id: "desc").page(params[:page]).per(20)
  end

  def show
    @blog = Blog.find(params[:id])

    rescue ActiveRecord::RecordNotFound , NoMethodError => e
      redirect_to root_path
    rescue => e
      redirect_to root_path
  end

  def genre
    @blog = Blog.find_by(genre_id: params[:id])
    @blogs = Blog.where(genre_id: params[:id]).order(created_at: :desc)
  end

  def owner
  end

  def search
    @blogs = Blog.search(params[:keyword])
  end


end

app/helpers/_markdown_helper.rb
require 'rouge'
require 'rouge/plugins/redcarpet'

class RougeHTML < Redcarpet::Render::HTML
  include Rouge::Plugins::Redcarpet
end

module MarkdownHelper
  def markdown(text)
    render_options = {
      no_links: false,
      hard_wrap: true,
      
    }
    extensions = {
      hard_wrap: true,
      autolink: true,
      no_intra_emphasis: true,
      tables: true,
      fenced_code_blocks: true,
      disable_indented_code_blocks: true,
      strikethrough: true,
      lax_spacing: true,
      spece_after_headers: true,
      quote: true,
      footnotes: true,
      highlight: true,
      underline: true,
      with_toc_data: true,
      prettify: true
    }

    renderer = RougeHTML.new(render_options)
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end
  
end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '')
    base_title = 'MochaBlog'

    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/admin/blogs/edit.html.erb
<div class="new-post-page">
  <p class="new-post-page-title">Edit Screen</p>
  <%= form_with model: [:admin, @blog], class: 'admin-form', local: true do |f| %>
    <div class="form-contents">
      <%= f.text_field :title, placeholder: 'Title', id: "title", required: true %>
      <%= f.text_field :description, placeholder: 'Description', id: "description", required: true %>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class: "genre_select"}) %>
      <div class='img-preview' id='img-preview'></div>
      <label class="select-file">Image
      <%= f.file_field :image, class: 'hidden', id: "image", required: true %>
      </label>
      <%= f.submit "SEND", class: "send-submit" %>
    </div>
    <div class="code-block" >
      <div class="create-new-text">
      <%= f.text_area :text, placeholder: "Text", class: "text", id: "user_answer_code", required: true %>
      </div>
      <div class="create-new-text">
        <div class="preview"></div>
        <div id="code_markdown"></div> 
      </div>
    </div>
  <% end %>
</div>
<%= content_for(:title, 'Edit') %>

app/views/admin/blogs/new.html.erb
<div class="new-post-page">
  <p class="new-post-page-title">New Post Screen</p>
  <%= form_with url: admin_blogs_path, class: 'admin-form', id: 'img-select', local: true do |f| %>
    <div class="form-contents">
      <%= f.text_field :title, placeholder: 'Title', id: "title", required: true %>
      <%= f.text_field :description, placeholder: 'Description', id: "description", required: true %>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class: "genre_select"}) %>
      <div class='img-preview' id='img-preview'></div>
      <label class="select-file">Image
      <%= f.file_field :image, class: 'hidden', id: "image", required: true %>
      </label>
      <%= f.submit "SEND", class: "send-submit" %>
    </div>
    
    <div class="code-block" >
      <div class="create-new-text">
      <%= f.text_area :text, placeholder: "Text", class: "text", id: "user_answer_code", required: true %>
      </div>
      <div class="create-new-text">
        <div class="preview"></div>
        <div id="code_markdown"></div> 
      </div>
    </div>
  <% end %>
</div>
<%= content_for(:title, 'New Post') %>

app/views/blogs/_site_right.html.erb
<div class='site-right-box'>
  <div class='blog-owner'>
    <div class='owner-img-box'>
      <%= image_tag "amoka.jpeg",  class: 'owner-img' , alt: "Oparetor Image" %>
    </div>
    <div class='owner-description'>
      <span>どうも。モカです。<br>日々、プログラミング学習しています。</span>
    </div>
  </div>
  <div class='search-box'>
    <%= form_with url: search_blogs_path, method: :get, class: 'search-form', local: true do |f| %>
      <%= f.text_field :keyword, placeholder: "Title Seach", class: "search-input" %><br>
      <div class='btn-box'>
        <%= f.submit "Seach", class: "btn-gray" %>
      </div>
      </label>
    <% end %>
  </div>
</div>

app/views/blogs/genre.html.erb
<div class='blog-contents'>
  <span class='new-article'><%= @blog.genre.name %></span>
  <% if @blog.blank? %>
    投稿はありません。
  <% else %>
    <div class='blog-lists' >
      <div class='article-list'>
        <% @blogs.each do |blog| %>
          <div class='list'>
            <%= link_to blog_path(blog.id), class: 'blog-title-img' do %>
              <div>
                <%= image_tag blog.image.variant(resize: '120x120') %>
              </div>
              <div class='blog-title'>
                <%= blog.title %>
                <div class='blog-description'><%= blog.description %></div>
                <div class='blog-date'><%= blog.created_at.strftime("投稿日：%Y/%m/%d") %></div>
              </div>

            <% end %>
          </div>
        <% end %>
      </div>
      <%= render "site_right" %>
    </div>
    <div class="social">
      <a href="https://twitter.com/share?&text=[MochaBlog]&hashtags=MochaBlog" rel="nofollow" target="_blank"><i class="fa-brands fa-twitter"></i></a>
      <a href="http://line.me/R/msg/text/?%0a[MochaBlog]" target="_blank" rel="nofollow noopener"><i class="fa-brands fa-line"></i></a>
    </div>
  <% end %>

</div>
<%= content_for(:title, @blog.genre.name) %>

app/views/blogs/index.html.erb
<div class="blog-contents">
  <span class='new-article'>New Article</span>
  <div class='blog-lists' >
    <div class='article-list'>
      <% @blogs.each do |blog| %>
        <div class='list'>
          <%= link_to blog_path(blog.id), class: 'blog-title-img', method: :get do %>
            <div>
              <%= image_tag blog.image.variant(resize: '120x120') if blog.image.attached? %>
            </div>
            <div class='blog-title'>
              <%= blog.title %>
              <div class='blog-description'><%= blog.description %></div>
              <div class='blog-date'><%= blog.created_at.strftime("投稿日：%Y/%m/%d") %></div>
            </div>
          <% end %>
          <% if user_signed_in? && current_user.admin? %>
            <%= link_to 'EDIT', edit_admin_blog_path(blog.id), class: 'admin-only edit', data: {"turbolinks" => false}, method: :get %>
            <%= link_to 'DELETE', admin_blog_path(blog.id), class: 'admin-only delete', data: { confirm: 'Is it okay if I delete this article?' }, method: :delete %>
          <% end %>
        </div>
      <% end %>
      <%= paginate @blogs %>
    </div>

    <%= render "site_right"%>
  </div>
  <div class="social">
    <a href="https://twitter.com/share?&text=[MochaBlog]&hashtags=MochaBlog" rel="nofollow" target="_blank"><i class="fa-brands fa-twitter"></i></a>
    <a href="http://line.me/R/msg/text/?%0a[MochaBlog]" target="_blank" rel="nofollow noopener"><i class="fa-brands fa-line"></i></a>
  </div>
</div>
<%= content_for(:title, 'New Article') %>

app/views/blogs/owner.html.erb
<div class="blog-contents">
  <span class='new-article'>Site Author</span>
  <div class='blog-lists' >
    <div class='owner-article-list'>
      <div class='profile-card' >
        <h2 class='profile'>Profile</h2>
      </div>
      <ul class='profile-contents'>
        <li class='profile-list '>
          Name : Mocha
        </li>
        <li class='profile-list'>
          Attribute : Minecrafter
        </li>
        <li class='profile-list'>
          FreeTime : HorseRace
        </li>
        <li class='profile-list'>
          Favorite Animal : Horse, Rabbit
        </li>
        <li class='profile-description'>
          Thank you for reading this blog.<br>
          On a daily basis, this blog will output what we have learned.<br>
          I would appreciate it if you could contact me via Twitter if there are any incorrect descriptions or comments.
        </li>
      </ul>

      <div class='profile-card' >
        <h2 class='profile'>Experience</h2>
      </div>
      <ul class='profile-contents'>
        <li class='profile-list '>
          Java,  Ruby,  JavaScript,  HTML,  CSS
        </li>
      </ul>

      <div class='profile-card' >
        <h2 class='profile'>Minecraft</h2>
      </div>
      <ul class='profile-contents'>
        <li class='profile-list'>
          I'm working on a minecraft modding in Java.<br>
          It's too much fun!<br>
          It's really touching to actually move what you make!
        </li>
      </ul>
    </div>


    <div class='site-right-box'>
      <div class='blog-owner'>
        <div class='owner-img-box'>
          <%= image_tag "amoka.jpeg",  class: 'owner-img' , alt: "Oparetor Image" %>
        </div>
        <div class='owner-description'>
          <span>チャンレジ精神豊富なおっさんです。<br>愛しいうさぎのためにも頑張ります!</span>
        </div>
      </div>
    </div>
  </div>
</div>
<%= content_for(:title, '運営者情報') %>

app/views/blogs/search.html.erb
<div class="blog-contents">
  <span class='new-article'>Search Results</span>
  <div class='blog-lists' >
    <div class='article-list'>
      <% @blogs.each do |blog| %>
        <div class='list'>
          <%= link_to blog_path(blog.id), class: 'blog-title-img', method: :get do %>
            <div>
              <%= image_tag blog.image.variant(resize: '120x120') if blog.image.attached? %>
            </div>
            <div class='blog-title'>
              <%= blog.title %>
              <div class='blog-description'><%= blog.description %></div>
            </div>
          <% end %>
          <% if user_signed_in? && current_user.admin? %>
            <%= link_to 'EDIT', edit_admin_blog_path(blog.id), class: 'admin-only edit', data: {"turbolinks" => false}, method: :get %>
            <%= link_to 'DELETE', admin_blog_path(blog.id), class: 'admin-only delete', data: { confirm: 'Is it okay if I delete this article?' }, method: :delete %>
          <% end %>
        </div>
      <% end %>
      <% if @blogs.blank? %>
          お探しのページはありませんでした。
      <% end %>
    </div>
    <%= render 'site_right'%>
  </div>
</div>
<%= content_for(:title, 'Search Results') %>

app/views/blogs/show.html.erb
<div class='blog-contents'>
  <div class='blog-lists'>
    <div class='show-article-list'>
      <div class='show-list'>
        <div>
          <%= image_tag @blog.image.variant(resize: '120x120') if @blog.image.attached? %>
        </div>
        <div class='show-blog-title'>
          <h3><%= @blog.title %></h3>
          <div class='blog-description'><%= @blog.description %></div>
          <div class='blog-date'><%= @blog.created_at.strftime("投稿日：%Y/%m/%d") %></div>
        </div>

      </div>
      <div class='blog-markdown-text'>
        <%= markdown(@blog.text).html_safe %>
      </div>
    </div>
    <%= render "site_right" %>
  </div>
  <div class="social">
    <a href="https://twitter.com/share?&text=[MochaBlog]&hashtags=MochaBlog" rel="nofollow" target="_blank"><i class="fa-brands fa-twitter"></i></a>
    <a href="http://line.me/R/msg/text/?%0a[MochaBlog]" target="_blank" rel="nofollow noopener"><i class="fa-brands fa-line"></i></a>
  </div>
</div>
<%= content_for(:title, @blog.title) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head prefix="og:http://ogp.me/ns#">
    <title><%= page_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta property="og:title" content="MochaBlog" />
    <meta property="og:type" content="blog"/>
    <meta property="og:description" content="プログラミング学習やマイクラ(java版)のMOD制作の内容をアウトプットしていくブログです。"/>
    <meta property="og:url" content="http://52.192.233.63/"/>
    <meta name="keywords" content="Java,minecraft,マイクラ,プログラミング,blog,ブログ"/>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    
    <script src='https://cdnjs.cloudflare.com/ajax/libs/marked/2.0.1/marked.js'></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.6.0/styles/monokai-sublime.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.6.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
  <header class='top-page-header'>
    <div>
      <%= link_to 'MochaBlog', "/", class: "mocha-title-name", id:"site-title" %>
    </div>
    <div>
      <% if flash[:notice] %>
        <p id="notice">
          <%= flash[:notice] %>
        </p>
      <% end %>
    </div>
    <div class="admin-login">
      <% if user_signed_in? && current_user.admin? %>
        <li><%= link_to 'New Post', new_admin_blog_path, class: "admin-new-post admin-btn", data: {"turbolinks" => false} %>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "admin-logout admin-btn" %></li>
      <% end %>
    </div>
    <div id="nav-wrapper" class="nav-wrapper" >
      <i class="fa-solid fa-magnifying-glass top-page-search-icon" id="js-gear"></i>
      <nav class="sp-nav">
        <i class="fa-regular fa-circle-xmark" id="js-black-bg"></i>
        <div class="smart-search">
          <%= form_with url: search_blogs_path, method: :get, class: 'smart-search-form', local: true do |f| %>
            <%= f.text_field :keyword, placeholder: "キーワード", class: 'search-keyword' %>
              <label for="seach-bottun" class="icon-label"><i class="fa-solid fa-magnifying-glass in-sp-nav-icon"></i></label>
              <%= f.submit id: "seach-bottun", class: "btn-hidden" %>
          <% end %>
        </div>
      </nav>
      <div class="black-bg" id="black-bg-close"></div>
    </div>
  </header>
  <div class="navi__wrap">
    <ul class="navi__lists">
      <li class="navi__list"><a>Programming</a>
        <ul class="dropdown__lists">
          <li class="dropdown__list"><%= link_to 'Java', '/blogs/genre/2' %></li>
        </ul>
      </li>
      <li class="navi__list"><a>Minecraft</a>
        <ul class="dropdown__lists">
          <li class="dropdown__list"><%= link_to 'Modding', '/blogs/genre/3' %></li>
        </ul>
      </li>
      <li class="navi__list"><a>Other</a>
        <ul class="dropdown__lists">
          <li class="dropdown__list"><%= link_to 'Twitter', 'https://twitter.com/sfsfsilk', data: { confirm: 'Twitterへ移動します。よろしいですか?' } %></li>
          <li class="dropdown__list"><%= link_to 'Site Author', '/owner' %></li>
        </ul>
      </li>
    </ul>
  </div>
    <%= yield %>
  <footer class="top-page-footer">
    <div>
      <h2>Mocha</h2>
    </div>
    <div>
      <h2>© 2023 MochaBlog</h2>
    </div>
  </footer>
  </body>
</html>